project_id = "rarkpesqxjpdfvxslllv"

[functions.send-team-freeze-notification]
verify_jwt = false

[functions.send-challenge-notification]
verify_jwt = false

[functions.seed-test-data]
verify_jwt = true

[functions.delete-account]
verify_jwt = false