project_id = "rarkpesqxjpdfvxslllv"

[functions.send-team-freeze-notification]
verify_jwt = false

[functions.send-challenge-notification]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.send-contact-message]
verify_jwt = false

[functions.seed-review-account]
verify_jwt = false